pipeline{
        agent {
            label "linux_slave"
        }
        stages{
            stage('Prepare') {
            steps {
                script {
                    echo 'Cleaning workspace...'
                    cleanWs()
                }
            }
        }
            stage("SCM Checkout"){
                steps{
                    echo "Checkout code from github"
                    git "https://github.com/Hubcodee/Jenkins_Sessions_2024.git"
                }
        }
            stage("Setup Infratsructure"){
                steps{
                    echo "Setting up infrastructure"
                    sh "yum install httpd -y"
                    sh "systemctl start httpd"
                    sh "systemctl enable httpd"
                }
        }
            stage("Deploy the code"){
                steps{
                    echo "Deploying the code"
                    sh "cp -r Lecture_4/* /var/www/html/"
                }
            }
        }
}